//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_TRACK
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string LINK_IMG { get; set; }
        public string LINK { get; set; }
        public Nullable<byte> RANKK { get; set; }
        public Nullable<double> COST { get; set; }
    
        public virtual TRACK TRACK { get; set; }
    }
}
