//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public byte LEVEL_ { get; set; }
        public Nullable<byte> SALE_INDEX { get; set; }
        public Nullable<double> CONDITION { get; set; }
    }
}
