//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOW
    {
        public int ID { get; set; }
        public Nullable<int> ID_ARTIST { get; set; }
        public string NAME { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
    
        public virtual ARTIST ARTIST { get; set; }
    }
}
