//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATISTIC_ARTIST
    {
        public int ID_ARTIST { get; set; }
        public Nullable<int> CLI_PER_MON { get; set; }
        public Nullable<int> CLI_ALL { get; set; }
        public Nullable<int> BUY_PER_MON { get; set; }
        public Nullable<int> BUY_ALL { get; set; }
        public Nullable<int> POINT_MONTH { get; set; }
    
        public virtual ARTIST ARTIST { get; set; }
    }
}
