//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOP_6_DJ
    {
        public int RANK { get; set; }
        public Nullable<int> ID_ARTIST { get; set; }
        public string NAME_ARTIST { get; set; }
        public string IMG { get; set; }
    }
}
