//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRACK()
        {
            this.HISTORY_USER = new HashSet<HISTORY_USER>();
            this.REMIXes = new HashSet<REMIX>();
            this.TRACK_ARTIST = new HashSet<TRACK_ARTIST>();
            this.USERs = new HashSet<USER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> TEMPO { get; set; }
        public string KEY_ { get; set; }
        public Nullable<double> COST { get; set; }
        public string LINK { get; set; }
        public Nullable<System.DateTime> DATE_RELEASE { get; set; }
        public string LINK_IMG { get; set; }
        public string DESCRIPT { get; set; }
        public string LENGTH { get; set; }
        public string GENRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY_USER> HISTORY_USER { get; set; }
        public virtual NEW_TRACK NEW_TRACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REMIX> REMIXes { get; set; }
        public virtual STATISTIC_TRACK STATISTIC_TRACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACK_ARTIST> TRACK_ARTIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
    }
}
